config/routes.rb
Food::Application.routes.draw do
  
 root to: 'students#index'

  resources :interventions, :behaviors, :students, :mstudents

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  get 'say/goodbye' => 'say#goodbye'

  get 'mstudents/aut/:id' => 'mstudents#aut#:id'

  get 'static_pages/customize' => 'static_pages#customize'
  get 'static_pages/report' => 'static_pages#report'
  get 'static_pages/allusers' => 'static_pages#allusers'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	  before_filter :authenticate_user!
	def customize
	end

	def report
  #  @students = Student.where(user_id: current_user.id
    @mstudents = Mstudent.all.where(user_id: current_user.id)
    @users = User.find(current_user.id)
    @students = @users.students
    @students2 = @students.where("created_at >= ?", 1.week.ago.utc).order("count_all desc").group('firstname').count.take(10)
    @students3 = @students.where("created_at >= ?", 1.month.ago.utc).order("count_all desc").group('firstname').count.take(10)
    @behive = @students.where("created_at >= ?", 1.week.ago.utc).order("count_all desc").group('behive').count.take(10)
    @behive2 = @students.where("created_at >= ?", 1.month.ago.utc).order("count_all desc").group('behive').count.take(10)
    @studentlist = @users.students.group(:firstname)

    # @students = @users.students.order("count_all desc").count(group: :firstname)
  # @students2 = @students.count(:group => :firstname)
  #	@students2 = @students.where("firstname = :firstname")
  #  @students = @users.students.where("created_at >= ?", Time.zone.now.beginning_of_day).order("id DESC")
 
    @interventions = Intervention.all

   # @EVENT_COLORS = "%06x" % (rand * 0xffffff)
   @event_colors = "red", "green", "blue"

	end

      def restrict_access
      redirect_to root_path, :alert => "Access denied"
      end


  def allusers
    if current_user.id != 1
     redirect_to root_path 
    else 
      @users = User.all
    end
  end




end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/allusers.html.erb
<% @users.each do |user| %>

<%= user.email %> | 
<%= time_ago_in_words(user.last_sign_in_at) %> | 
<%= user.sign_in_count %> |
<%= user.school %>
<br>

<% end %>

app/views/static_pages/customize.html.erb
<br>

<i class="fa fa-users fa-2x"></i> <%= link_to('Students', mstudents_path, :class => :customizelinks) %><br> Add new students<br><br>
<i class="fa fa-meh-o fa-2x"></i> <%= link_to('Behaviors', behaviors_path, :class => :customizelinks) %><br> Add/modify behaviors<br><br>
<i class="fa fa-check-square fa-2x"></i> <%= link_to('Interventions', interventions_path, :class => :customizelinks) %><br> Add/modify interventions<br><br>

<i class="fa fa-wrench fa-2x"></i> <%= link_to('Profile', edit_user_registration_path, :class => :customizelinks) %> <br>
Edit/Delete your profile <br><br><br><br><br>

<p style="font-size:10px">Email picotrend@gmail.com with any feedback suggestions or <a href="http://www.twitter.com/dhold" target="new">@dhold</a> on twitter.</p>

app/views/static_pages/report.html.erb
<% if @students.count <= 4 %>
<br>
<div class="behavereport">
	<p> Customize your picotrend to view pretty reports! Track at least five behaviors to begin viewing reports!!!</p>
	<p> In the mean-time, view this sample pie chart! <p></div><br>


		<canvas id="canvas5" height="250" width="250"></canvas>

<font style="background-color:<%= cycle("#F38630", "#E0E4CC", "#69D2E7") %>">I need</font><font style="background-color:<%= cycle("#F38630", "#E0E4CC", "#69D2E7") %>"> to start</font><font style="background-color:<%= cycle("#F38630", "#E0E4CC", "#69D2E7") %>"> tracking students.</font>
	<script>

		var pieData = [
				{
					value: 30,
					color:"#F38630"
				},
				{
					value : 50,
					color : "#E0E4CC"
				},
				{
					value : 100,
					color : "#69D2E7"
				}
			
			];

	var myPie = new Chart(document.getElementById("canvas5").getContext("2d")).Pie(pieData);
	
	</script>




<% else %>
	
<div class="behavereport">
<strong>Weekly Student Behavior Frequency</strong><br><br>

<%= @students2[4] %>

<% @students2.each do |student| %>
<font style="background-color:<%= cycle("#80C4C4", "#EB99C2", "#CCFF66", "#7A7ACC") %>"><%= student[0] %> | <%= student[1] %></font>
<br>

<% end %>
</div>
<br>
	<canvas id="canvas" height="250" width="500"></canvas>


	<script>

		var lineChartData = {
			labels : [<% @students2[0...-1].each do |student| %>
			"<%=student[0]%>",
			<% end %>"<%= @students2.last[0] %>"],
			datasets : [
				{
					fillColor : "rgba(151,187,205,0.5)",
					strokeColor : "rgba(151,187,205,1)",
					pointColor : "rgba(151,187,205,1)",
					pointStrokeColor : "#fff",
					data : [<% @students2[0...-1].each do |student| %>
			<%= student[1] %>,<% end %><%= @students2.last[1] %>]
				}
			]
			
		}

	var myLine = new Chart(document.getElementById("canvas").getContext("2d")).Line(lineChartData);
	
	</script>




<div class="behavereport">
<br>
<strong>Weekly Most Frequent Behaviors:</strong> <br><br>

<% @behive.each do |behive| %>

<font style="background-color:<%= cycle("#80C4C4", "#EB99C2", "#CCFF66", "#7A7ACC") %>"><%= behive[0] %> | <%= behive[1] %></font>
<br>

<% end %>
</div>

<br>

		<canvas id="canvas3" height="250" width="250"></canvas>


	<script>

		var pieData = [
		<% @behive[0...-1].each do |behive| %>
				{
					value: <%= behive[1] %>,
					color: "<%= cycle("#80C4C4", "#EB99C2", "#CCFF66", "#7A7ACC") %>"
				}, <% end %>
				{
					value : <%= @behive.last[1] %>,
					color : "#7AA3CC"
				}
			
			];

	var myPie = new Chart(document.getElementById("canvas3").getContext("2d")).Pie(pieData);
	
	</script>


<div class="behavereport">
<strong>Monthly Student Behavior Frequency</strong><br><br>

<% @students3.each do |student| %>

<font style="background-color:<%= cycle("#80C4C4", "#EB99C2", "#CCFF66", "#7A7ACC") %>"><%= student[0] %> | <%= student[1] %></font>
<br>

<% end %>
</div>
<br>
	<canvas id="canvas2" height="250" width="500"></canvas>


	<script>

		var lineChartData = {
			labels : [<% @students3[0...-1].each do |student| %>
			"<%=student[0]%>",
			<% end %>"<%= @students3.last[0] %>"],
			datasets : [
				{
					fillColor : "rgba(151,187,205,0.5)",
					strokeColor : "rgba(151,187,205,1)",
					pointColor : "rgba(151,187,205,1)",
					pointStrokeColor : "#fff",
					data : [<% @students3[0...-1].each do |student| %>
			<%= student[1] %>,<% end %><%= @students3.last[1] %>]
				}
			]
			
		}

	var myLine = new Chart(document.getElementById("canvas2").getContext("2d")).Line(lineChartData);
	
	</script>



<div class="behavereport">
<br>
<strong>Monthly Most Frequent Behaviors:</strong> <br><br>

<% @behive2.each do |behive| %>

<font style="background-color:<%= cycle("#80C4C4", "#EB99C2", "#CCFF66", "#7A7ACC") %>"><%= behive[0] %> | <%= behive[1] %></font>
<br>

<% end %>

</div>
<br>
		<canvas id="canvas4" height="250" width="250"></canvas>


	<script>

		var pieData = [
		<% @behive2[0...-1].each do |behive| %>
				{
					value: <%= behive[1] %>,
					color: "<%= cycle("#80C4C4", "#EB99C2", "#CCFF66", "#7A7ACC") %>"
				}, <% end %>
				{
					value : <%= @behive2.last[1] %>,
					color : "#7AA3CC"
				}
			
			];

	var myPie = new Chart(document.getElementById("canvas4").getContext("2d")).Pie(pieData);
	
	</script>

	<% end %>