config/routes.rb
Food::Application.routes.draw do
  
 root to: 'students#index'

  resources :interventions, :behaviors, :students, :mstudents

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  get 'say/goodbye' => 'say#goodbye'

  get 'mstudents/aut/:id' => 'mstudents#aut#:id'

  get 'static_pages/customize' => 'static_pages#customize'
  get 'static_pages/report' => 'static_pages#report'
  get 'static_pages/allusers' => 'static_pages#allusers'

end

app/models/behavior.rb
class Behavior < ActiveRecord::Base
	belongs_to :student
	belongs_to :user
end

app/controllers/behaviors_controller.rb
class BehaviorsController < ApplicationController
  before_action :set_behavior, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /behaviors
  # GET /behaviors.json
  def index
    @user = current_user.id
    @behaviors = Behavior.where(user_id: current_user.id)
  end

  # GET /behaviors/1
  # GET /behaviors/1.json
  def show
  @fod = Behavior.all.where(user_id: current_user.id)
  @fod.find(params[:id], params[:user_id])
  end

  # GET /behaviors/new
  def new
    @user = current_user.id
    @behavior = Behavior.new
  end

  # GET /behaviors/1/edit
  def edit
    @fod = Behavior.all.where(user_id: current_user.id)
    @fod.find(params[:id], params[:user_id])
  end

  # POST /behaviors
  # POST /behaviors.json
  def create
    @behavior = Behavior.new(behavior_params)

    respond_to do |format|
      if @behavior.save
        format.html { redirect_to @behavior, notice: 'Behavior was successfully created.' }
        format.json { render action: 'show', status: :created, location: @behavior }
      else
        format.html { render action: 'new' }
        format.json { render json: @behavior.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /behaviors/1
  # PATCH/PUT /behaviors/1.json
  def update
    respond_to do |format|
      if @behavior.update(behavior_params)
        format.html { redirect_to @behavior, notice: 'Behavior was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @behavior.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /behaviors/1
  # DELETE /behaviors/1.json
  def destroy
    @behavior.destroy
    respond_to do |format|
      format.html { redirect_to behaviors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_behavior
      @behavior = Behavior.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def behavior_params
      params.require(:behavior).permit(:behavior, :intervention, :consequence, :user_id)
    end
end

app/helpers/behaviors_helper.rb
module BehaviorsHelper
end

app/views/behaviors/_form.html.erb
<%= form_for(@behavior) do |f| %>
  <% if @behavior.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@behavior.errors.count, "error") %> prohibited this behavior from being saved:</h2>

      <ul>
      <% @behavior.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="field">
<%= f.hidden_field :user_id, :value => @user %>
</div>

  <div class="field">
    <%= f.label :behavior %><br>
    <%= f.text_area :behavior, :size => "30x2", :maxlength => 250 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/behaviors/edit.html.erb
<h1>Editing behavior</h1>

<%= render 'form' %>

<%= link_to 'Show', @behavior %> |
<%= link_to 'Back', behaviors_path %>

app/views/behaviors/index.html.erb
<h1>Listing Behaviors</h1>

<table>
  <thead>
    <tr>
      <th>Behavior</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @behaviors.each do |behavior| %>
      <tr>
        <td><%= behavior.behavior %></td>
        <td><%= link_to 'View', behavior %></td>
        <td><%= link_to 'Edit', edit_behavior_path(behavior) %></td>
        <td><%= link_to 'Delete', behavior, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Behavior', new_behavior_path %>

app/views/behaviors/new.html.erb
<h1>New Behavior</h1>

<%= render 'form' %>

<%= link_to 'Back', behaviors_path %>

app/views/behaviors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Behavior:</strong>
  <%= @behavior.behavior %>
</p>

<%= link_to 'Edit', edit_behavior_path(@behavior) %> |
<%= link_to 'Back', behaviors_path %>