config/routes.rb
Food::Application.routes.draw do
  
 root to: 'students#index'

  resources :interventions, :behaviors, :students, :mstudents

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  get 'say/goodbye' => 'say#goodbye'

  get 'mstudents/aut/:id' => 'mstudents#aut#:id'

  get 'static_pages/customize' => 'static_pages#customize'
  get 'static_pages/report' => 'static_pages#report'
  get 'static_pages/allusers' => 'static_pages#allusers'

end

app/models/intervention.rb
class Intervention < ActiveRecord::Base
	belongs_to :student
	belongs_to :user
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_action :set_intervention, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /interventions
  # GET /interventions.json
  def index
    @interventions = Intervention.all.where(user_id: current_user.id)
  end

  # GET /interventions/1
  # GET /interventions/1.json
  def show
  @fod = Intervention.all.where(user_id: current_user.id)
  @fod.find(params[:id], params[:user_id])
  end

  # GET /interventions/new
  def new
    @user = current_user.id
    @intervention = Intervention.new
  end

  # GET /interventions/1/edit
  def edit
  @fod = Intervention.all.where(user_id: current_user.id)
  @fod.find(params[:id], params[:user_id])
  end

  # POST /interventions
  # POST /interventions.json
  def create
    @intervention = Intervention.new(intervention_params)

    respond_to do |format|
      if @intervention.save
        format.html { redirect_to @intervention, notice: 'Intervention was successfully created.' }
        format.json { render action: 'show', status: :created, location: @intervention }
      else
        format.html { render action: 'new' }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interventions/1
  # PATCH/PUT /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to @intervention, notice: 'Intervention was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1
  # DELETE /interventions/1.json
  def destroy
    @intervention.destroy
    respond_to do |format|
      format.html { redirect_to interventions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def intervention_params
      params.require(:intervention).permit(:sfname, :slname, :intervention, :intervention_type, :user_id)
    end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<%= form_for(@intervention) do |f| %>
  <% if @intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% @intervention.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 <div class="field">
<%= f.hidden_field :user_id, :value => @user %>
</div>

  <div class="field">
    <%= f.label :intervention %><br>
    <%= f.text_area :intervention, :size => "30x2", :maxlength => 250 %>
  </div>
<!--
  <div class="field">
    <%= check_box_tag("prox") %>
    <%= label_tag(:intervention, "Proximity Control") %>
  </div>
-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interventions/edit.html.erb
<h1>Editing intervention</h1>

<%= render 'form' %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<h1>Listing interventions</h1>

<table>
  <thead>
    <tr>
      <th>Intervention</th>

    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= intervention.intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td><%= link_to 'Delete', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb
<h1>New intervention</h1>

<%= render 'form' %>

<%= link_to 'Back', interventions_path %>

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Intervention:</strong>
  <%= @intervention.intervention %>
</p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>