config/routes.rb
Food::Application.routes.draw do
  
 root to: 'students#index'

  resources :interventions, :behaviors, :students, :mstudents

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  get 'say/goodbye' => 'say#goodbye'

  get 'mstudents/aut/:id' => 'mstudents#aut#:id'

  get 'static_pages/customize' => 'static_pages#customize'
  get 'static_pages/report' => 'static_pages#report'
  get 'static_pages/allusers' => 'static_pages#allusers'

end

app/models/mstudent.rb
class Mstudent < ActiveRecord::Base
	def fullname
	[fname, lname].join(" ")
	end
	belongs_to :student
	belongs_to :user
end

app/controllers/mstudents_controller.rb
require 'role_model'

class MstudentsController < ApplicationController
  before_action :set_mstudent, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /mstudents
  # GET /mstudents.json


  def index
    @mstudents = Mstudent.all.where(user_id: current_user.id)
  end

  def aut
  end

 
  # GET /mstudents/1
  # GET /mstudents/1.json
  def show
  @fod = Mstudent.all.where(user_id: current_user.id)
  @fod.find(params[:id], params[:user_id])
  end

  # GET /mstudents/new
  def new
    @user = current_user.id
    @mstudent = Mstudent.new
  end

  # GET /mstudents/1/edit
  def edit
  @fod = Mstudent.all.where(user_id: current_user.id)
  @fod.find(params[:id], params[:user_id])
   # authorize! :update, @article
  end

  # POST /mstudents
  # POST /mstudents.json
  def create
    @mstudent = Mstudent.new(mstudent_params)

    respond_to do |format|
      if @mstudent.save
        format.html { redirect_to @mstudent, notice: 'Mstudent was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mstudent }
      else
        format.html { render action: 'new' }
        format.json { render json: @mstudent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mstudents/1
  # PATCH/PUT /mstudents/1.json
  def update
    respond_to do |format|
      if @mstudent.update(mstudent_params)
        format.html { redirect_to @mstudent, notice: 'Mstudent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mstudent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mstudents/1
  # DELETE /mstudents/1.json
  def destroy
    @mstudent.destroy
    respond_to do |format|
      format.html { redirect_to mstudents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_mstudent
      @mstudent = Mstudent.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def mstudent_params
      params.require(:mstudent).permit(:fname, :lname, :user_id)
    end
end

app/helpers/mstudents_helper.rb
module MstudentsHelper
end

app/views/mstudents/_form.html.erb
<%= form_for(@mstudent) do |f| %>
  <% if @mstudent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mstudent.errors.count, "error") %> prohibited this mstudent from being saved:</h2>

      <ul>
      <% @mstudent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
<%= f.hidden_field :user_id, :value => @user %>
</div>

  <div class="field">
    <%= f.label :First %><br>
    <%= f.text_field :fname, :maxlength => 30 %>
  </div>
  <div class="field">
    <%= f.label :Last %><br>
    <%= f.text_field :lname, :maxlength => 30 %>
  </div>
  <div class="actions">
    <%= f.submit "Create Student" %>
  </div>
<% end %>

app/views/mstudents/aut.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lname:</strong>
  <%= @mstudent.lname %>
</p>

app/views/mstudents/aut.json.erb
json.extract! @mstudent, :fname, :lname, :created_at, :updated_at

app/views/mstudents/customize.html.erb
     hey

           <!-- <li><%= link_to('Tracker', students_path) %></li>
            <li><%= link_to('Students', mstudents_path) %></li>
            <li><%= link_to('Interventions', interventions_path) %></li>
           	<li><%= link_to('Profile', edit_user_registration_path) %> </li>
           	-->

app/views/mstudents/edit.html.erb
<h1>Editing Students</h1>

<%= render 'form' %>

<%= link_to 'Show', @mstudent %> |
<%= link_to 'Back', mstudents_path %>

app/views/mstudents/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mstudents.each do |mstudent| %>
      <tr>
        <td><%= mstudent.fname %></td>
        <td><%= mstudent.lname %></td>
        <td><%= link_to 'Edit', edit_mstudent_path(mstudent) %></td>
        <td><%= link_to 'Delete', mstudent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add a new student', new_mstudent_path %>

app/views/mstudents/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', mstudents_path %>

app/views/mstudents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @mstudent.fname %>   <%= @mstudent.lname %>

</p>


<%= link_to 'Edit', edit_mstudent_path(@mstudent) %> |
<%= link_to 'Back', mstudents_path %>